export const APP_NAME = "5240 PcOff Agent";

export const PATHS = {
  config: "config.json",
  state: "state.json",
  logsDir: "logs",
  guardDir: "guard",
  integrity: "guard/integrity.json",
  watchList: "guard/watch-list.json",
  isolationMode: "guard/isolation-mode.json",
  updateDir: "update",
  retryQueue: "update/retry-queue.json",
  installerRegistry: "installer-registry.json",
  leaveSeatQueue: "leave-seat-queue.jsonl",
  offlineState: "offline-state.json",
  emergencyUnlockState: "emergency-unlock-state.json"
} as const;

export const LOG_CODES = {
  // 기본 이벤트
  APP_START: "APP_START",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
  LOGOUT: "LOGOUT",
  LOCK_TRIGGERED: "LOCK_TRIGGERED",
  UNLOCK_TRIGGERED: "UNLOCK_TRIGGERED",

  // 업데이트 (FR-03)
  UPDATE_FOUND: "UPDATE_FOUND",
  UPDATE_DOWNLOADED: "UPDATE_DOWNLOADED",
  UPDATE_APPLIED: "UPDATE_APPLIED",
  UPDATE_FAILED: "UPDATE_FAILED",

  // 비밀번호 변경 (FR-04)
  PASSWORD_CHANGE_DETECTED: "PASSWORD_CHANGE_DETECTED",
  PASSWORD_CONFIRM_DONE: "PASSWORD_CONFIRM_DONE",

  // Agent Guard (FR-07)
  AGENT_TAMPER_DETECTED: "AGENT_TAMPER_DETECTED",
  AGENT_TAMPER_ATTEMPT: "AGENT_TAMPER_ATTEMPT",
  AGENT_RECOVERED: "AGENT_RECOVERED",
  AGENT_RECOVERY_FAILED: "AGENT_RECOVERY_FAILED",
  AGENT_STOP_ATTEMPT: "AGENT_STOP_ATTEMPT",

  // Ops Observer (FR-08)
  OFFLINE_DETECTED: "OFFLINE_DETECTED",
  CRASH_DETECTED: "CRASH_DETECTED",
  HEARTBEAT: "HEARTBEAT",

  // 설치자 레지스트리 (FR-09)
  INSTALLER_REGISTRY_SYNC: "INSTALLER_REGISTRY_SYNC",
  INSTALLER_REGISTRY_FAIL: "INSTALLER_REGISTRY_FAIL",

  // 인스톨/언인스톨 (FR-19)
  INSTALL_START: "INSTALL_START",
  INSTALL_SUCCESS: "INSTALL_SUCCESS",
  INSTALL_FAIL: "INSTALL_FAIL",
  INSTALL_ROLLBACK: "INSTALL_ROLLBACK",
  UNINSTALL_REQUEST: "UNINSTALL_REQUEST",
  UNINSTALL_ATTEMPT: "UNINSTALL_ATTEMPT",
  UNINSTALL_SUCCESS: "UNINSTALL_SUCCESS",
  UNINSTALL_FAIL: "UNINSTALL_FAIL",
  SELF_HEAL_SUCCESS: "SELF_HEAL_SUCCESS",
  SELF_HEAL_FAIL: "SELF_HEAL_FAIL",
  ISOLATION_MODE_ENTERED: "ISOLATION_MODE_ENTERED",

  // 이석 감지 (FR-11)
  LEAVE_SEAT_DETECTED: "LEAVE_SEAT_DETECTED",
  LEAVE_SEAT_UNLOCK: "LEAVE_SEAT_UNLOCK",
  LEAVE_SEAT_REASON_SUBMITTED: "LEAVE_SEAT_REASON_SUBMITTED",
  LEAVE_SEAT_BREAK_EXEMPT: "LEAVE_SEAT_BREAK_EXEMPT",
  LEAVE_SEAT_IDLE_DETECTED: "LEAVE_SEAT_IDLE_DETECTED",
  LEAVE_SEAT_SLEEP_DETECTED: "LEAVE_SEAT_SLEEP_DETECTED",
  LEAVE_SEAT_RESUME_CHECKED: "LEAVE_SEAT_RESUME_CHECKED",
  LEAVE_SEAT_RELEASED: "LEAVE_SEAT_RELEASED",
  SLEEP_ENTERED: "SLEEP_ENTERED",
  SLEEP_RESUMED: "SLEEP_RESUMED",

  // 이석정보 서버 전송 (FR-12)
  LEAVE_SEAT_START: "LEAVE_SEAT_START",
  LEAVE_SEAT_END: "LEAVE_SEAT_END",
  LEAVE_SEAT_REPORT_FAILED: "LEAVE_SEAT_REPORT_FAILED",
  LEAVE_SEAT_REPORT_RETRY: "LEAVE_SEAT_REPORT_RETRY",

  // 오프라인 복구·잠금 (FR-17)
  OFFLINE_GRACE_STARTED: "OFFLINE_GRACE_STARTED",
  OFFLINE_RETRY: "OFFLINE_RETRY",
  OFFLINE_TIMEOUT_LOCK: "OFFLINE_TIMEOUT_LOCK",
  OFFLINE_RECOVERED: "OFFLINE_RECOVERED",

  // 긴급해제 (FR-15)
  EMERGENCY_UNLOCK_ATTEMPT: "EMERGENCY_UNLOCK_ATTEMPT",
  EMERGENCY_UNLOCK_SUCCESS: "EMERGENCY_UNLOCK_SUCCESS",
  EMERGENCY_UNLOCK_FAILED: "EMERGENCY_UNLOCK_FAILED",
  EMERGENCY_UNLOCK_LOCKED: "EMERGENCY_UNLOCK_LOCKED",
  EMERGENCY_UNLOCK_EXPIRED: "EMERGENCY_UNLOCK_EXPIRED",
  EMERGENCY_UNLOCK_EXPIRY_WARNING: "EMERGENCY_UNLOCK_EXPIRY_WARNING",

  // 트레이 작동정보 (FR-16)
  TRAY_INFO_OPENED: "TRAY_INFO_OPENED",
  TRAY_ATTENDANCE_REFRESHED: "TRAY_ATTENDANCE_REFRESHED",
  TRAY_MODE_CHANGED: "TRAY_MODE_CHANGED",

  // 시업/종업 화면 (FR-13)
  SCREEN_TYPE_BEFORE: "SCREEN_TYPE_BEFORE",
  SCREEN_TYPE_OFF: "SCREEN_TYPE_OFF",
  SCREEN_TYPE_USABLE: "SCREEN_TYPE_USABLE",
  SCREEN_TRANSITION: "SCREEN_TRANSITION",

  // 프로세스 Kill 통제 (FR-18)
  KILL_REQUEST_CREATED: "KILL_REQUEST_CREATED",
  KILL_OTP_SENT: "KILL_OTP_SENT",
  KILL_OTP_VERIFIED: "KILL_OTP_VERIFIED",
  KILL_OTP_FAILED: "KILL_OTP_FAILED",
  KILL_TOKEN_ISSUED: "KILL_TOKEN_ISSUED",
  KILL_EXECUTED: "KILL_EXECUTED",
  KILL_REJECTED: "KILL_REJECTED",
  KILL_ATTEMPT_BLOCKED: "KILL_ATTEMPT_BLOCKED"
} as const;
