export const APP_NAME = "5240 PcOff Agent";

export const PATHS = {
  config: "config.json",
  state: "state.json",
  logsDir: "logs",
  guardDir: "guard",
  integrity: "guard/integrity.json",
  watchList: "guard/watch-list.json",
  updateDir: "update",
  retryQueue: "update/retry-queue.json",
  installerRegistry: "installer-registry.json"
} as const;

export const LOG_CODES = {
  APP_START: "APP_START",
  UPDATE_FOUND: "UPDATE_FOUND",
  UPDATE_DOWNLOADED: "UPDATE_DOWNLOADED",
  UPDATE_APPLIED: "UPDATE_APPLIED",
  UPDATE_FAILED: "UPDATE_FAILED",
  PASSWORD_CHANGE_DETECTED: "PASSWORD_CHANGE_DETECTED",
  PASSWORD_CONFIRM_DONE: "PASSWORD_CONFIRM_DONE",
  AGENT_TAMPER_DETECTED: "AGENT_TAMPER_DETECTED",
  AGENT_TAMPER_ATTEMPT: "AGENT_TAMPER_ATTEMPT",
  AGENT_RECOVERED: "AGENT_RECOVERED",
  AGENT_RECOVERY_FAILED: "AGENT_RECOVERY_FAILED",
  AGENT_STOP_ATTEMPT: "AGENT_STOP_ATTEMPT",
  OFFLINE_DETECTED: "OFFLINE_DETECTED",
  CRASH_DETECTED: "CRASH_DETECTED",
  HEARTBEAT: "HEARTBEAT",
  INSTALLER_REGISTRY_SYNC: "INSTALLER_REGISTRY_SYNC",
  INSTALLER_REGISTRY_FAIL: "INSTALLER_REGISTRY_FAIL",
  LEAVE_SEAT_DETECTED: "LEAVE_SEAT_DETECTED",
  LEAVE_SEAT_UNLOCK: "LEAVE_SEAT_UNLOCK",
  LEAVE_SEAT_REASON_SUBMITTED: "LEAVE_SEAT_REASON_SUBMITTED",
  LEAVE_SEAT_BREAK_EXEMPT: "LEAVE_SEAT_BREAK_EXEMPT",
  LEAVE_SEAT_IDLE_DETECTED: "LEAVE_SEAT_IDLE_DETECTED",
  LEAVE_SEAT_SLEEP_DETECTED: "LEAVE_SEAT_SLEEP_DETECTED",
  LEAVE_SEAT_RESUME_CHECKED: "LEAVE_SEAT_RESUME_CHECKED",
  LEAVE_SEAT_RELEASED: "LEAVE_SEAT_RELEASED",
  SLEEP_ENTERED: "SLEEP_ENTERED",
  SLEEP_RESUMED: "SLEEP_RESUMED"
} as const;
